### ISSUE TITLE
What should we do with OroCRM and OroPlatform projects?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/marketing#421]
We currently have:

* https://symfony.com/projects/orocrm
* https://symfony.com/projects/oroplatform

I think this is confusing. I propose to remove OroPlatform project and keep only OroCRM.

**Comment by DimaSoroka** [comment]
hi @javiereguiluz , what is confusing about OroPlatform and OroCRM? There is one more project from Oro family - https://symfony.com/projects/orocommerce, will be happy to add proper clarifications.
