### ISSUE TITLE
Symfony.com Open Graph image

### ISSUE THREAD

**Issue by petk** [symfony/marketing#442]
Hello, 

any chance to re-scale and re-crop the current image used for open graph image:
http://symfony.com/images/v5/opengraph/symfony_logo_vertical.png

See this for more info:
- https://developers.facebook.com/docs/sharing/best-practices/#images
According to this information the best minimal image canvas size is 1200 x 630. I would suggest to crop the current logo horizontally to meet something of 1200px width or more (based on the previews).

Currently the logo is being cropped on the share. Thanks :)

**Comment by petk** [comment]
Hello, I've tested the OG image a bit and what would the proper size be. It turns out that 1500px x 800px (width x height) would be ideal fit. Example site is available at https://petk.github.io/testing/index.html

With such size the following is shown ok on FB:
![demo](https://user-images.githubusercontent.com/1614009/33585634-80873a36-d965-11e7-9c26-2846182fc13b.png)

Notice the current site symfony.com issue shared on Facebook:
![demo_2](https://user-images.githubusercontent.com/1614009/33585688-c3703514-d965-11e7-84ab-676fda141420.png)

Thanks for considering fixing this somehow...

**Comment by javiereguiluz** [comment]
@petk thank you very much for reporting this issue, for providing references and for fixing it. We're going to change the logo very soon (to use the 1500x800 size you recommended) and see how it goes.

Note to myself: in case this causes any problem on Twitter, use the `twitter:image` in addition to `og:image` to link to a different image. See: https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup.

**Comment by javiereguiluz** [comment]
Closing as fixed. Links shared on Twitter look OK too. @petk thanks again for your help.

**Comment by petk** [comment]
Works great. Thank you :+1:
