### ISSUE TITLE
It's not clear how to get updates for security advisories

### ISSUE THREAD

**Issue by iltar** [symfony/marketing#467]
Question from slack: _"Is there like a mailing list I can subscribe to to get notifications of Symfony security issues?"_

Page wise, you can see them at: https://symfony.com/blog/category/security-advisories. But there's no clear way of receiving updates regarding these CVEs. In order to receive updates regarding those security advisories, you have to register to the roadmap updates on: https://symfony.com/roadmap, where you have to manage your subscriptions. On the following page (https://symfony.com/account/notifications) you can specify _what_ you want to receive.

My proposal is to add a link on the security advisories page, to that same page. This way it should be easier to register for those specific updates.

**Comment by javiereguiluz** [comment]
@iltar thanks for proposing this improvement. We've added a new message to tell about the email notifications. Once deployed, it'd look like this:

![security-notifications](https://user-images.githubusercontent.com/73419/42168643-d71081a4-7e11-11e8-8d7a-b5662d7110c8.png)

**Comment by iltar** [comment]
Awesome, thanks!

**Comment by TheLalaMan** [comment]
Great!
