### ISSUE TITLE
Matomo logo broken on homepage

### ISSUE THREAD

**Issue by Mx-Glitter** [symfony/marketing#471]
![capture d ecran 2018-07-13 a 14 17 40](https://user-images.githubusercontent.com/4671739/42691267-a03d6694-86a7-11e8-8835-6728ab72a08f.png)

It seems that home page is not using the same images as the ones in `/projects`. It looks for `https://symfony.com/images/v5/projects-logos/logo-matomo.png` which does not exist. `https://symfony.com/images/v5/projects-logos/logo-piwik.png` still exists by the way. I don't know how to fix this as it does not look like it's in this repository

**Comment by fabpot** [comment]
We noticed the same. We are working on a fix.
