### ISSUE TITLE
[News] Markdown special characters corrupt text in release announcements

### ISSUE THREAD

**Issue by guilliamxavier** [symfony/marketing#475]
On the blog, in the latest release announcement http://symfony.com/blog/symfony-4-1-3-released we see "REMOT _ADDR" (should be "REMOTE_ADDR").

The problem appeared between April 30 and May 7 of this year:

- until http://symfony.com/blog/symfony-3-4-9-released we could read e.g.
    "Add CODE_OF_CONDUCT.md"
- since http://symfony.com/blog/symfony-4-1-0-beta1-released we are seeing e.g.
    "Add COD _O _CONDUCT.md",
    "Add choic _translatio _locale option",
    "Search for other SYMFON _ env vars" (original text also had an asterisk after the underscore)...

Only in http://symfony.com/blog/category/releases (does not happen in other types of news, for example in http://symfony.com/blog/a-week-of-symfony-604-23-29-july-2018 we can read "describe weak_vendors properly").

This has been signaled several times in comments without response, so I'm trying here.

**Comment by guilliamxavier** [comment]
@fabpot Monthes later, the problem is still there on each new release announcement!

Problematic symbols: _ (underscore), * (asterisk), \ (backslash)... even when inside a pair of ` (backticks).

Various examples (I give the link to the news, which contains a link to the PR):

| Release | PR excerpt<br>News excerpt |
| --- |:--- |
| [4.2.2](https://symfony.com/blog/symfony-4-2-2-released) | the mb_internal_encoding is<br>the m _interna _encoding is |
| [4.2.1](https://symfony.com/blog/symfony-4-2-1-released) | Allow `ConstraintViolation::__toString()` to<br>Allow ConstraintViolation::toString() to |
| [4.2.0-RC1](https://symfony.com/blog/symfony-4-2-0-rc1-released) | in RememberMe\DoctrineTokenProvider<br>in RememberMeDoctrineTokenProvider |
| [4.2.0-BETA1](https://symfony.com/blog/symfony-4-2-0-beta1-released) | Deprecate `Symfony\Bundle\FrameworkBundle\Controller\Controller`<br>Deprecate SymfonyBundleFrameworkBundleControllerController |
| [4.1.0-BETA1](https://symfony.com/blog/symfony-4-1-0-beta1-released) | [Serializer] `default_constructor_arguments` context<br>[Serializer] defaul _constructo _arguments context |
| [3.4.9](https://symfony.com/blog/symfony-3-4-9-released) | on *nix OS<br>on nix OS |

I cannot even propose a fix since I don't know what you are using to convert the MarkDown to HTML... How can I help?

**Comment by javiereguiluz** [comment]
@guilliamxavier thanks for compiling all the errors in your comment. We're working on a fix for this in the private repo of symfony.com. I can't tell you when/if this fix will be merged, but your comment helped us a lot and I want to thank you for that.

**Comment by guilliamxavier** [comment]
@javiereguiluz glad I could help. Thank you for your reply.

**Comment by guilliamxavier** [comment]
Since you closed this issue, I expected the problem to be finally fixed... but I see it's still there on https://symfony.com/blog/symfony-5-0-8-released (e.g. "COMPOSER_BINARY" has become "COMPOSE _BINARY") :confused:

How is the news generated from the GitHub release notes? Are you using an open-source tool? Or if it's a custom script in a private repo, can't you publish just the relevant part so that we can get it fixed at last?
