### ISSUE TITLE
Proposal to add a new open source project

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/marketing#480]
A user contacted us via email to ask us if it would be possible to include their open source Symfony-based project in the list of projects made with Symfony: https://github.com/uvdesk/community-skeleton

The UVdesk project (https://github.com/uvdesk) looks very recent and the project has less GitHub stars and downloads than we usually require to add projects to the list ... but I'm creating this issue nonetheless so we can decide about this. Thanks!

**Comment by javiereguiluz** [comment]
Let's close this as "won't fix" and reconsider it when the project has more stars and downloads. Thanks.

**Comment by papnoisanjeev** [comment]
@javiereguiluz,
Now we have got more than 6k downloads and about to reach 250 GitHub star. Could you please reconsider this project in the list of Symfony projects?
Thanks!
