### ISSUE TITLE
Broken links from https://symfony.com/about to sensiolabs.com

### ISSUE THREAD

**Issue by GromNaN** [symfony/marketing#505]
Hi,

I hit some broken links in the "About SensioLabs" section of the [About page](https://symfony.com/about).

* `https://sensiolabs.com/en/a_propos/nous_aimons_le_concret.html`
* `https://sensiolabs.com/en/clients/clients.html`

Does Symfony still belongs to SensioLabs ?

**Comment by fabpot** [comment]
No, Symfony does not belong to SensioLabs anymore. @javiereguiluz Can you update the contents?

**Comment by javiereguiluz** [comment]
Closing this one as fixed because we updated that and other pages too. Thanks!
