### ISSUE TITLE
Project "Mothership" looks abandoned

### ISSUE THREAD

**Issue by nclavaud** [symfony/marketing#522]
Hi there,

While browsing through the list of e-commerce projects using Symfony, I found [Mothership](https://symfony.com/projects/mothership) but the website link is broken.

Also, the last commit on the [github project](https://github.com/mothership-ec/mothership) is 5 years old.

Looks like this project is not relevant anymore.

**Comment by fabpot** [comment]
Can you create a PR to remove the project?

**Comment by nclavaud** [comment]
Sure, here it is.
